#!/bin/bash
###########################################################################################
####                                    CODE TYPE                                      ####
####                     wallclock, benchmark, convection, output                      ####
###########################################################################################
code_type="wallclock"
fcompiler="gfortran-12"
ccompiler="gcc-12"

###########################################################################################
####                                PATHS TO LIBRARIES                                 ####
###########################################################################################
mathpath=kernels/math
sphidxpath=kernels/sph
fftpath=kernels/latgrid/mod/fft
legepath=kernels/latgrid/mod/legepoly
sphsvtpath=kernels/sphsvt
latgridpath=kernels/latgrid
radgridpath=kernels/radgrid
grdsubspath=kernels/gridsubs
eqspath=kernels/equations
iopath=kernels/binaryio
objpath=kernels/object
outputpath=kernels/output
oceanpath=ocean
codepath=codes

###########################################################################################
####                                  DIRS STRUCTURE                                   ####
###########################################################################################
lvlC=( "${mathpath}/smod/codelets" 
       "${legepath}/smod/cores" 
       "${fftpath}/smod/cores" 
       "${sphsvtpath}/smod/codelets" 
       "${grdsubspath}/smod/codelets" 
       "${objpath}/smod/codelets" )

lvlF=( "${mathpath}/smod" 
       "${sphidxpath}/smod" 
       "${fftpath}/smod/init" 
       "${fftpath}/smod/transform" 
       "${legepath}/smod/init" 
       "${legepath}/smod/indexing" 
       "${legepath}/smod/transform" 
       "${sphsvtpath}/smod/init" 
       "${sphsvtpath}/smod/cleb" 
       "${sphsvtpath}/smod/transform" 
       "${latgridpath}/smod/" 
       "${radgridpath}/smod/init" 
       "${radgridpath}/smod/differences" 
       "${radgridpath}/smod/integration" 
       "${radgridpath}/smod/interpolation" 
       "${grdsubspath}/smod/cores" 
       "${eqspath}/smod/init" 
       "${eqspath}/smod/cores" 
       "${iopath}/smod" 
       "${objpath}/smod/init" 
       "${objpath}/smod/forces" 
       "${objpath}/smod/operators" 
       "${objpath}/smod/matrices" 
       "${objpath}/smod/output" 
       "${objpath}/smod/solvers" 
       "${objpath}/smod/variables" 
       "${objpath}/smod/dvariablesdr" 
       "${objpath}/smod/dvariablesdS" 
       "${oceanpath}/smod/" 
       "${outputpath}/smod" )

###########################################################################################
####                                 INSTRUCTIONS CHECK                                ####
###########################################################################################
macros=$($ccompiler -march=native -dM -E -x c /dev/null)

echo "$macros" | grep -q "__FMA__"     && instructions="$instructions -D__FMA__"
echo "$macros" | grep -q "__AVX512F__" && instructions="$instructions -D__AVX512F__"

###########################################################################################
####                                 COMPILERS SET UP                                  ####
###########################################################################################
flags="-Ofast -march=native -mprefer-vector-width=512 -mno-vzeroupper -fstrict-aliasing \
       -fno-tree-loop-distribute-patterns -fcx-limited-range -fno-bounds-check -fopenmp \
       -fomit-frame-pointer -fno-stack-protector -fargument-noalias-global -flto=auto \
       -fwhole-program -D$code_type $instructions -cpp"

fcompile="$fcompiler $flags"
ccompile="$ccompiler $flags -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-memmove"

###########################################################################################
####                               1. COMPILING INTERFACES                             ####
###########################################################################################
$fcompile -c "${mathpath}/math.f90"
$fcompile -c "${sphidxpath}/sph.f90"
$fcompile -c "${fftpath}/fourier_transform.f90"
$fcompile -c "${legepath}/lege_poly.f90"
$fcompile -c "${radgridpath}/radial_grid.f90"
$fcompile -c "${grdsubspath}/gridsubs.f90"
$fcompile -c "${eqspath}/equations.f90"
$fcompile -c "${iopath}/binaryio.f90"
$fcompile -c "${oceanpath}/ocean_parms.f90"
$fcompile -c "${outputpath}/output_paths.f90"
$fcompile -c "${sphsvtpath}/sphsvt.f90"
$fcompile -c "${latgridpath}/lateral_grid.f90"
$fcompile -c "${outputpath}/output_mod.f90"
$fcompile -c "${objpath}/physicalobject.f90"
$fcompile -c "${oceanpath}/ocean.f90"

###########################################################################################
####                           2. COMPILING IMPLEMENTATIONS                            ####
###########################################################################################
find "${lvlC[@]}" -maxdepth 1 -name "*.c"   -print0 | xargs -0 -r -P 0 -n 1 $ccompile -c &
find "${lvlF[@]}" -maxdepth 1 -name "*.f90" -print0 | xargs -0 -r -P 0 -n 1 $fcompile -c &

wait

###########################################################################################
####                                 3. LINKING                                        ####
###########################################################################################
case $code_type in
       
       wallclock)
              $fcompile ${codepath}/BielyKralik.f90 *.o -o "Test_wallclock.out"
       ;;
       
       output)
              $fcompile ${codepath}/OutputOcean.f90 *.o -o "Test_output.out"
              
              rm -f temp_averaged.spec velc_averaged.spec flux_averaged.spec || true
       ;;
       
       *)
              $fcompile ${codepath}/BielyKralik.f90 *.o -o "Test_"$code_type".out"
              
              rm -rf data || true
              
              mkdir -p data/data_ocean_temp data/data_ocean_veloc \
                            data/data_ocean_fluxu data/data_ocean_fluxd
       ;;

esac

###########################################################################################
####                                       CLEANING                                    ####
###########################################################################################
rm *.smod *.mod *.o || true