#!/bin/bash
###########################################################################################
####                                    CODE TYPE                                      ####
####                     wallclock, benchmark, convection, output                      ####
###########################################################################################
code_type="benchmark"
fcompiler="gfortran-12"
ccompiler="gcc-12"

###########################################################################################
####                                 INSTRUCTIONS CHECK                                ####
###########################################################################################
if $ccompiler -march=native -dM -E -x c /dev/null | grep -q "__AVX512F__"; then
       instructions="-D$code_type -D__FMA__ -D__AVX512F__"
elif $ccompiler -march=native -dM -E -x c /dev/null | grep -q "__FMA__"; then
       instructions="-D$code_type -D__FMA__"
else
       instructions="-D$code_type"
fi

###########################################################################################
####                                 COMPILERS SET UP                                  ####
###########################################################################################
flags="-Ofast -march=native -mprefer-vector-width=512 -mno-vzeroupper -fstrict-aliasing \
       -fno-tree-loop-distribute-patterns -fcx-limited-range -fno-bounds-check -fopenmp \
       -fomit-frame-pointer -fno-stack-protector -fargument-noalias-global -flto=auto \
       -fwhole-program $instructions -cpp"

fcompile="$fcompiler $flags"
ccompile="$ccompiler $flags -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-memmove"

###########################################################################################
####                                COMPILE DIR STRUCTURE                              ####
###########################################################################################
function fcompile_lvl() {
       
       local -n dirs=$1
       
       for dir in "${dirs[@]}"
              do
                     find "$dir" -maxdepth 1 -name "*.f90" -exec $fcompile -c {} + &
              done
       
}

function ccompile_lvl() {
       
       local -n dirs=$1
       
       for dir in "${dirs[@]}"
              do
                     find "$dir" -maxdepth 1 -name "*.c" -exec $ccompile -c {} + &
              done
       
}

###########################################################################################
####                                PATHS TO LIBRARIES                                 ####
###########################################################################################
mathpath=kernels/math
sphidxpath=kernels/sph
fftpath=kernels/latgrid/mod/fft
legepath=kernels/latgrid/mod/legepoly
sphsvtpath=kernels/sphsvt
latgridpath=kernels/latgrid
radgridpath=kernels/radgrid
grdsubspath=kernels/gridsubs
eqspath=kernels/equations
iopath=kernels/binaryio
objpath=kernels/object
outputpath=kernels/output
oceanpath=ocean
codepath=codes

###########################################################################################
####                                  DIRS STRUCTURE                                   ####
###########################################################################################
lvlC=( "${mathpath}/smod/codelets" 
       "${legepath}/smod/cores" 
       "${fftpath}/smod/cores" 
       "${sphsvtpath}/smod/codelets" 
       "${grdsubspath}/smod/codelets" 
       "${objpath}/smod/codelets" )

lvlF=( "${mathpath}/smod" 
       "${sphidxpath}/smod" 
       "${fftpath}/smod/init" 
       "${fftpath}/smod/transform" 
       "${legepath}/smod/init" 
       "${legepath}/smod/indexing" 
       "${legepath}/smod/transform" 
       "${sphsvtpath}/smod/init" 
       "${sphsvtpath}/smod/cleb" 
       "${sphsvtpath}/smod/transform" 
       "${latgridpath}/smod/" 
       "${radgridpath}/smod/init" 
       "${radgridpath}/smod/differences" 
       "${radgridpath}/smod/integration" 
       "${radgridpath}/smod/interpolation" 
       "${grdsubspath}/smod/cores" 
       "${eqspath}/smod/init" 
       "${eqspath}/smod/cores" 
       "${iopath}/smod" 
       "${objpath}/smod/init" 
       "${objpath}/smod/forces" 
       "${objpath}/smod/operators" 
       "${objpath}/smod/matrices" 
       "${objpath}/smod/output" 
       "${objpath}/smod/solvers" 
       "${objpath}/smod/variables" 
       "${objpath}/smod/dvariablesdr" 
       "${objpath}/smod/dvariablesdS" 
       "${oceanpath}/smod/" 
       "${outputpath}/smod" )

###########################################################################################
####                               1. COMPILING INTERFACES                             ####
###########################################################################################
$fcompile -c ${mathpath}/math.f90
$fcompile -c ${sphidxpath}/sph.f90
$fcompile -c ${fftpath}/fourier_transform.f90
$fcompile -c ${legepath}/lege_poly.f90
$fcompile -c ${sphsvtpath}/sphsvt.f90
$fcompile -c ${latgridpath}/lateral_grid.f90
$fcompile -c ${radgridpath}/radial_grid.f90
$fcompile -c ${grdsubspath}/gridsubs.f90
$fcompile -c ${eqspath}/equations.f90
$fcompile -c ${iopath}/binaryio.f90
$fcompile -c ${objpath}/physicalobject.f90
$fcompile -c ${oceanpath}/ocean_parms.f90
$fcompile -c ${outputpath}/output_paths.f90
$fcompile -c ${outputpath}/output_mod.f90
$fcompile -c ${oceanpath}/ocean.f90

###########################################################################################
####                           2. COMPILING IMPLEMENTATIONS                            ####
###########################################################################################
ccompile_lvl lvlC
fcompile_lvl lvlF

wait

###########################################################################################
####                                 3. LINKING                                        ####
###########################################################################################
case $code_type in
       
       wallclock)
              $fcompile ${codepath}/BielyKralik.f90 *.o -o "Test_wallclock.out"
       ;;
       
       output)
              $fcompile ${codepath}/OutputOcean.f90 *.o -o "Test_output.out"
              
              rm -f temp_averaged.spec velc_averaged.spec flux_averaged.spec || true
       ;;
       
       *)
              $fcompile ${codepath}/BielyKralik.f90 *.o -o "Test_"$code_type".out"
              
              rm -rf data || true
              
              mkdir -p data/data_ocean_temp data/data_ocean_veloc \
                            data/data_ocean_fluxu data/data_ocean_fluxd
       ;;

esac

###########################################################################################
####                                       CLEANING                                    ####
###########################################################################################
rm *.smod *.mod *.o || true