#!/bin/bash
###########################################################################################
####                                  REMOVE OLD FILES                                 ####
###########################################################################################
rm -f temp_averaged.spec velc_averaged.spec flux_averaged.spec || true

###########################################################################################
####                   COMPILATION OF THE BASELINE AND LINKING                         ####
###########################################################################################
source ./kernels/shell/compiler.sh

libfcompile kernels/math/math math.f90
libfcompile kernels/math/sph/ sph.f90

$fcompile -c code/ocean/ocean_constants.f90
$fcompile -c output/mod/Paths.f90
$fcompile -c output/mod/OutputMod.f90

$fcompile output/OutputOcean.f90 *.o -o code_out

###########################################################################################
####                                    CLEANING                                       ####
###########################################################################################
rm *.mod *.o *.smod