#!/bin/bash
###########################################################################################
####                             SPECIFY FROM/TO FOR DELETE                            ####
###########################################################################################
delstart="1"
delend="0"

###########################################################################################
####                             DELETING SPECIFIED FILES                              ####
###########################################################################################
for i in $(seq $delstart $delend);
do
    rm data/data_ocean_temp/Temp-$i.dat
    rm data/data_ocean_veloc/Velc-$i.dat
    rm data/data_ocean_fluxu/Fluxu-$i.dat
    rm data/data_ocean_fluxd/Fluxd-$i.dat
done