#!/bin/bash
###########################################################################################
####                                    CODE TYPE                                      ####
####                          wallclock, benchmark, convection                         ####
####                                                                                   ####
####                                MEMORY ALIGNEMENT                                  ####
####                                   mem32, mem64                                    ####
####                                                                                   ####
####                                      KERNEL                                       ####
####                               kernelC (mem32, mem64)                              ####
####                               kernelF (mem32, mem64)                              ####
####                                                                                   ####
####                                    COMPILER                                       ####
####                                  gfortran, ifx                                    ####
###########################################################################################
code_type="benchmark"
memory="mem32"
kernel="kernelC"
compiler="gfortran"

###########################################################################################
####                              PREPARING THE COMPILER                               ####
###########################################################################################
source ./shell/compiler.sh

###########################################################################################
####                                PATHS TO LIBRARIES                                 ####
###########################################################################################
mathpath=kernels/math
sphidxpath=kernels/sph
fftpath=kernels/latgrid/mod/fft
legepath=kernels/latgrid/mod/legepoly
sphsvtpath=kernels/sphsvt
latgridpath=kernels/latgrid
radgridpath=kernels/radgrid
eqspath=kernels/equations
iopath=kernels/binaryio
objpath=kernels/object
oceanpath=code/ocean
codepath=code/codes

###########################################################################################
####                                  DIRS STRUCTURE                                   ####
###########################################################################################
lvlM=( "${mathpath}/smod" 
       "${legepath}/smod/codelets" )

lvl0=( "${fftpath}/smod/codelets" )

lvl1=( "${sphidxpath}/smod" 
       "${fftpath}/smod/init" 
       "${fftpath}/smod/cores" 
       "${fftpath}/smod/transform" 
       "${legepath}/smod/init" 
       "${legepath}/smod/indexing" 
       "${legepath}/smod/transform" 
       "${sphsvtpath}/smod/init" 
       "${sphsvtpath}/smod/cleb" 
       "${sphsvtpath}/smod/transform" 
       "${latgridpath}/smod/" 
       "${radgridpath}/smod/init" 
       "${radgridpath}/smod/differences" 
       "${radgridpath}/smod/integration" 
       "${radgridpath}/smod/interpolation" 
       "${eqspath}/smod/init" 
       "${eqspath}/smod/cores" 
       "${iopath}/smod" 
       "${objpath}/smod/init" 
       "${objpath}/smod/forces" 
       "${objpath}/smod/operators" 
       "${objpath}/smod/matrices" 
       "${objpath}/smod/output" 
       "${objpath}/smod/solvers" 
       "${objpath}/smod/variables" 
       "${objpath}/smod/dvariablesdr" 
       "${objpath}/smod/dvariablesdS" 
       "${oceanpath}/smod/" )

###########################################################################################
####                               1. COMPILING INTERFACES                             ####
###########################################################################################
$fcompile -c ${mathpath}/math.f90
$fcompile -c ${sphidxpath}/sph.f90
$fcompile -c ${fftpath}/fourier_transform.f90
$fcompile -c ${legepath}/lege_poly.f90
$fcompile -c ${sphsvtpath}/sphsvt.f90
$fcompile -c ${latgridpath}/lateral_grid.f90
$fcompile -c ${radgridpath}/radial_grid.f90
$fcompile -c ${eqspath}/equations.f90
$fcompile -c ${iopath}/binaryio.f90
$fcompile -c ${objpath}/physicalobject.f90
$fcompile -c ${oceanpath}/ocean_parms.f90
$fcompile -c ${oceanpath}/ocean.f90

###########################################################################################
####                        2. COMPILING LVL0 IMPLEMENTATIONS                          ####
###########################################################################################
compile_lvl CF lvlM

if [ "$kernel" = "kernelC" ]
    then
        compile_lvl C lvl0
    else
        compile_lvl F lvl0
fi

###########################################################################################
####                        3. COMPILING LVL1 IMPLEMENTATIONS                          ####
###########################################################################################
compile_lvl F lvl1

###########################################################################################
####                                 4. LINKING                                        ####
###########################################################################################
$fcompile ${codepath}/BielyKralik.f90 *.o -o "Test_"$code_type".out"

###########################################################################################
####                             PREPARING THE DIRECTORIES                             ####
###########################################################################################
if [ "$code_type" != "wallclock" ]
    then
        rm -rf data || true
        
        mkdir -p data/data_ocean_temp \
                 data/data_ocean_veloc \
                 data/data_ocean_fluxu \
                 data/data_ocean_fluxd
fi

###########################################################################################
####                                       CLEANING                                    ####
###########################################################################################
libclean
