#!/bin/bash
###########################################################################################
####                              POSSIBLE CODE SETTINGS                               ####
####                            test_speed, ocean_convection                           ####
###########################################################################################
code_type="test_speed"

###########################################################################################
####                               INSTRUCTIONS SET UP                                 ####
####                                avx, avx2, avx512                                  ####
###########################################################################################
instructions="avx2"

###########################################################################################
####                                 COMPILER SET UP                                   ####
###########################################################################################
fcompile="gfortran-12 -Ofast \
                      -march=native \
                      -mprefer-vector-width=512 \
                      -fno-bounds-check \
                      -flto=auto \
                      -fwhole-program \
                      -fopenmp \
                      -D$instructions \
                      -cpp"

###########################################################################################
####                    COMPILATION OF THE BASELINE, DIRS SET UP                       ####
###########################################################################################
$fcompile -c kernels/math/processor/alignement.f90
wait

$fcompile -c kernels/math/math/math.f90
$fcompile -c $(find kernels/math/math/smod/. -type f) &
wait

$fcompile -c kernels/math/sph/sph.f90
$fcompile -c $(find kernels/math/sph/smod/. -type f) &
wait

$fcompile -c kernels/math/fft/fourier_transform.f90
$fcompile -c $(find kernels/math/fft/smod/. -type f) &
wait

$fcompile -c kernels/math/legepoly/lege_poly.f90
$fcompile -c $(find kernels/math/legepoly/smod/. -type f) &
wait

$fcompile -c kernels/math/sphsvt/mod/cleb.f90
$fcompile -c $(find kernels/math/sphsvt/mod/smod/. -type f) &
wait

$fcompile -c kernels/math/sphsvt/sphsvt.f90
$fcompile -c $(find kernels/math/sphsvt/smod/. -type f) &
wait

$fcompile -c kernels/math/lu_matrix/matrix.f90
$fcompile -c $(find kernels/math/lu_matrix/smod/. -type f) &
wait

$fcompile -c kernels/grid/radial/radial_grid.f90
$fcompile -c $(find kernels/grid/radial/smod/. -type f) &
wait

$fcompile -c kernels/grid/lateral/mod/grid_ops.f90
$fcompile -c $(find kernels/grid/lateral/mod/smod/. -type f) &
wait

$fcompile -c kernels/grid/lateral/lateral_grid.f90
$fcompile -c $(find kernels/grid/lateral/smod/. -type f) &
wait

$fcompile -c kernels/equations/solution/solution.f90
$fcompile -c $(find kernels/equations/solution/smod/. -type f) &
wait

$fcompile -c kernels/equations/matrices/matrices.f90
$fcompile -c $(find kernels/equations/matrices/smod/. -type f) &
wait

$fcompile -c kernels/object/physicalobject.f90
$fcompile -c $(find kernels/object/smod/. -type f) &
wait

$fcompile -c code/ocean/mod/ocean_constants.f90
$fcompile -c code/ocean/mod/ocean.f90
$fcompile -c $(find code/ocean/mod/smod/. -type f) &
wait

#rm -r -f data || true

###########################################################################################
####                                    LINKING                                        ####
###########################################################################################
case $code_type in

    test_speed)
        
        $fcompile code/codes/BielyKralik_speedTest.f90 *.o -o Test_speed
        
    ;;
    
    ocean_convection)
        mkdir data

        mkdir data/data_ocean_temp
        mkdir data/data_ocean_veloc
        mkdir data/data_ocean_fluxu
        mkdir data/data_ocean_fluxd
        
        $fcompile code/codes/BielyKralik_oceanConv.f90 *.o -o Test_convection
    ;;
    
esac

###########################################################################################
####                                    CLEANING                                       ####
###########################################################################################
rm *.smod *.mod *.o
