#!/bin/bash
###########################################################################################
####                              POSSIBLE CODE SETTINGS                               ####
####                            test_speed, ocean_convection                           ####
###########################################################################################
code_type="ocean_convection"

###########################################################################################
####                               INSTRUCTIONS SET UP                                 ####
####                                avx, avx2, avx512                                  ####
###########################################################################################
instructions="avx2"

###########################################################################################
####                                 COMPILER SET UP                                   ####
###########################################################################################
fcompile="gfortran-12 -Ofast \
                      -march=native \
                      -mprefer-vector-width=512 \
                      -fno-bounds-check \
                      -flto=auto \
                      -fwhole-program \
                      -fopenmp \
                      -D$instructions \
                      -cpp"

###########################################################################################
####                    COMPILATION OF THE BASELINE, DIRS SET UP                       ####
###########################################################################################
$fcompile -c kernels/math/processor/alignement.f90
wait

$fcompile -c kernels/math/math/math.f90
  $fcompile -c kernels/math/math/smod/math@allocator1.f90 &
  $fcompile -c kernels/math/math/smod/math@allocator2.f90 &
  $fcompile -c kernels/math/math/smod/math@conversions.f90 &
  $fcompile -c kernels/math/math/smod/math@nulify.f90 &
wait

$fcompile -c kernels/math/sph/sph_indexing.f90 &
$fcompile -c kernels/math/sph/sph_norms.f90 &
$fcompile -c kernels/math/sph/sph_ezvv.f90 &
wait

$fcompile -c kernels/math/fft/fourier_transform.f90
  $fcompile -c kernels/math/fft/smod/init/fourier_transform@init.f90 &
  $fcompile -c kernels/math/fft/smod/codelets/fourier_transform@fxi.f90 &
  $fcompile -c kernels/math/fft/smod/codelets/fourier_transform@fx2.f90 &
  $fcompile -c kernels/math/fft/smod/codelets/fourier_transform@fx3.f90 &
  $fcompile -c kernels/math/fft/smod/codelets/fourier_transform@fx4.f90 &
  $fcompile -c kernels/math/fft/smod/codelets/fourier_transform@fx5.f90 &
  $fcompile -c kernels/math/fft/smod/cores/fourier_transform@fxtal.f90 &
  $fcompile -c kernels/math/fft/smod/cores/fourier_transform@fxshf.f90 &
  $fcompile -c kernels/math/fft/smod/transforms/fourier_transform@r2c.f90 &
  $fcompile -c kernels/math/fft/smod/transforms/fourier_transform@c2r.f90 &
wait

$fcompile -c kernels/math/legepoly/lege_poly.f90
  $fcompile -c kernels/math/legepoly/smod/init/lege_poly@init.f90 &
  $fcompile -c kernels/math/legepoly/smod/init/lege_poly@roots.f90 &
  $fcompile -c kernels/math/legepoly/smod/init/lege_poly@coeffs.f90 &
  $fcompile -c kernels/math/legepoly/smod/indexing/lege_poly@allocators.f90 &
  $fcompile -c kernels/math/legepoly/smod/indexing/lege_poly@c2r.f90 &
  $fcompile -c kernels/math/legepoly/smod/indexing/lege_poly@r2c.f90 &
  $fcompile -c kernels/math/legepoly/smod/cores/lege_poly@bwd.f90 &
  $fcompile -c kernels/math/legepoly/smod/cores/lege_poly@fwd.f90 &
  $fcompile -c kernels/math/legepoly/smod/codelets/lege_poly@poly_mm.f90 &
  $fcompile -c kernels/math/legepoly/smod/codelets/lege_poly@poly_mj.f90 &
  $fcompile -c kernels/math/legepoly/smod/codelets/lege_poly@bwd_sum.f90 &
  $fcompile -c kernels/math/legepoly/smod/codelets/lege_poly@fwd_sum.f90 &
  $fcompile -c kernels/math/legepoly/smod/codelets/lege_poly@bwd_shuffle.f90 &
  $fcompile -c kernels/math/legepoly/smod/codelets/lege_poly@fwd_shuffle.f90 &
wait

$fcompile -c kernels/math/sphsvt/mod/cleb.f90
  $fcompile -c kernels/math/sphsvt/mod/smod/cleb@gordan1.f90 &
wait

$fcompile -c kernels/math/sphsvt/sphsvt.f90
  $fcompile -c kernels/math/sphsvt/smod/sphsvt@init.f90 &
  $fcompile -c kernels/math/sphsvt/smod/sphsvt@allocators.f90 &
  $fcompile -c kernels/math/sphsvt/smod/sphsvt@gradvec_to_vec.f90 &
  $fcompile -c kernels/math/sphsvt/smod/sphsvt@scal_to_scal.f90 &
  $fcompile -c kernels/math/sphsvt/smod/sphsvt@vec_to_vec.f90 &
  $fcompile -c kernels/math/sphsvt/smod/sphsvt@scal_to_vec.f90 &
  $fcompile -c kernels/math/sphsvt/smod/sphsvt@vec_to_scal.f90 &
wait

$fcompile -c kernels/math/lu_matrix/matrix.f90
  $fcompile -c kernels/math/lu_matrix/smod/matrix@init.f90 &
  $fcompile -c kernels/math/lu_matrix/smod/matrix@lu_decomp.f90 &
  $fcompile -c kernels/math/lu_matrix/smod/matrix@lu_solve.f90 &
  $fcompile -c kernels/math/lu_matrix/smod/matrix@mult.f90 &
wait

$fcompile -c kernels/grid/radial/radial_grid.f90
  $fcompile -c kernels/grid/radial/smod/init/radial_grid@init.f90 &
  $fcompile -c kernels/grid/radial/smod/differences/radial_grid@chebyschd.f90 &
  $fcompile -c kernels/grid/radial/smod/differences/radial_grid@interpd.f90 &
  $fcompile -c kernels/grid/radial/smod/integration/radial_grid@cvolint.f90 &
  $fcompile -c kernels/grid/radial/smod/integration/radial_grid@rvolint.f90 &
  $fcompile -c kernels/grid/radial/smod/integration/radial_grid@cradint.f90 &
  $fcompile -c kernels/grid/radial/smod/integration/radial_grid@rradint.f90 &
  $fcompile -c kernels/grid/radial/smod/interpolation/radial_grid@interpolation.f90 &
wait

$fcompile -c kernels/grid/lateral/mod/grid_ops.f90
  $fcompile -c kernels/grid/lateral/mod/smod/grid_ops@vcvv_vcvgv.f90 &
  $fcompile -c kernels/grid/lateral/mod/smod/grid_ops@vcvv_vcvxv.f90 &
wait

$fcompile -c kernels/grid/lateral/lateral_grid.f90
  $fcompile -c kernels/grid/lateral/smod/lateral_grid@init.f90 &
  $fcompile -c kernels/grid/lateral/smod/lateral_grid@transform.f90 &
  $fcompile -c kernels/grid/lateral/smod/lateral_grid@vcvv_vcvgv.f90 &
  $fcompile -c kernels/grid/lateral/smod/lateral_grid@vcvv_vcvxv.f90 &
wait

$fcompile -c kernels/equations/solution/solution.f90
  $fcompile -c kernels/equations/solution/smod/solution@init.f90 &
  $fcompile -c kernels/equations/solution/smod/solution@inittemp.f90 &
  $fcompile -c kernels/equations/solution/smod/solution@inittorr.f90 &
  $fcompile -c kernels/equations/solution/smod/solution@initmech.f90 &
  $fcompile -c kernels/equations/solution/smod/solution@temperature.f90 &
  $fcompile -c kernels/equations/solution/smod/solution@velocity.f90 &
wait

$fcompile -c kernels/equations/matrices/matrices.f90
  $fcompile -c kernels/equations/matrices/smod/matrices@init.f90 &
  $fcompile -c kernels/equations/matrices/smod/matrices@inittemp.f90 &
  $fcompile -c kernels/equations/matrices/smod/matrices@inittorr.f90 &
  $fcompile -c kernels/equations/matrices/smod/matrices@initmech.f90 &
wait

$fcompile -c kernels/object/physicalobject.f90
  $fcompile -c kernels/object/smod/physicalobject@init.f90 &
  
  $fcompile -c kernels/object/smod/equations/physicalobject@equations_mech.f90 &
  $fcompile -c kernels/object/smod/equations/physicalobject@equations_torr.f90 &
  $fcompile -c kernels/object/smod/equations/physicalobject@equations_temp.f90 &
  $fcompile -c kernels/object/smod/matrices/physicalobject@spheroidal_matrix.f90 &
  $fcompile -c kernels/object/smod/matrices/physicalobject@toroidal_matrix.f90 &
  $fcompile -c kernels/object/smod/matrices/physicalobject@thermal_matrix.f90 &
  $fcompile -c kernels/object/smod/diffusion/physicalobject@diffusion.f90 &
  $fcompile -c kernels/object/smod/forces/physicalobject@buoyancy.f90 &
  $fcompile -c kernels/object/smod/forces/physicalobject@coriolis.f90 &
  $fcompile -c kernels/object/smod/solvers/physicalobject@solver_mech.f90 &
  $fcompile -c kernels/object/smod/solvers/physicalobject@solver_torr.f90 &
  $fcompile -c kernels/object/smod/solvers/physicalobject@solver_temp.f90 &
  $fcompile -c kernels/object/smod/variables/physicalobject@temperature.f90 &
  $fcompile -c kernels/object/smod/variables/physicalobject@velocity.f90 &
  $fcompile -c kernels/object/smod/output/physicalobject@meassures.f90 &
  $fcompile -c kernels/object/smod/output/physicalobject@output.f90 &
wait

$fcompile -c code/ocean/mod/ocean_constants.f90
$fcompile -c code/ocean/mod/ocean.f90
  $fcompile -c code/ocean/mod/smod/ocean@init.f90 &
  $fcompile -c code/ocean/mod/smod/ocean@init_bnd.f90 &
  $fcompile -c code/ocean/mod/smod/ocean@init_state.f90 &
  $fcompile -c code/ocean/mod/smod/ocean@nonlin.f90 &
  $fcompile -c code/ocean/mod/smod/ocean@timescheme.f90 &
  $fcompile -c code/ocean/mod/smod/ocean@iter.f90 &
  $fcompile -c code/ocean/mod/smod/ocean@output.f90 &
wait

rm -r -f data || true

###########################################################################################
####                                    LINKING                                        ####
###########################################################################################
case $code_type in

    test_speed)
        
        $fcompile code/codes/BielyKralik_speedTest.f90 *.o -o Test_speed
        
    ;;
    
    ocean_convection)
        mkdir data

        mkdir data/data_ocean_temp
        mkdir data/data_ocean_veloc
        mkdir data/data_ocean_fluxu
        mkdir data/data_ocean_fluxd
        
        $fcompile code/codes/BielyKralik_oceanConv.f90 *.o -o Test_convection
    ;;
    
esac

###########################################################################################
####                                    CLEANING                                       ####
###########################################################################################
rm *.smod *.mod *.o

## Benchmarked: 1.9.2025
